
variables:
  version: "2018.7.12.5715"

stages:
  - debug
  - release

debug:
  stage: debug
  only:
  - dummy
  script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
  -
  - cd .\Bhbk.Lib.Helpers
  - dotnet build "Bhbk.Lib.Helpers.csproj" --configuration Debug --framework netstandard2.0
  #- dotnet test "Bhbk.Lib.Helpers.Tests.csproj" --configuration Debug --framework netstandard2.0
  -
  - cd ..\Bhbk.Lib.Waf
  - dotnet build "Bhbk.Lib.Waf.csproj" --configuration Debug --framework netcoreapp2.1
  - dotnet test "Bhbk.Lib.Waf.Tests.csproj" --configuration Debug --framework netcoreapp2.1

release:
  stage: release
  only:
  - dummy
  script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
  -
  - cd .\Bhbk.Lib.Helpers
  - dotnet build "Bhbk.Lib.Helpers.csproj" --configuration Release --framework netstandard2.0
  #- dotnet test "Bhbk.Lib.Helpers.Tests.csproj" --configuration Release --framework netstandard2.0
  - dotnet pack "Bhbk.Lib.Helpers.csproj" --configuration Release -p:PackageVersion=$version --output "..\\" -p:TargetFrameworks=netstandard2.0
  -
  - cd ..\Bhbk.Lib.Waf
  - dotnet build "Bhbk.Lib.Waf.csproj" --configuration Release --framework netcoreapp2.1
  - dotnet test "Bhbk.Lib.Waf.Tests.csproj" --configuration Release --framework netcoreapp2.1
  - dotnet pack "Bhbk.Lib.Waf.csproj" --configuration Release -p:PackageVersion=$version --output "..\\" -p:TargetFrameworks=netcoreapp2.1
  -
  - cd ..
  - nuget push *.nupkg -ApiKey %NUGET_FEED_KEY% -Source %NUGET_FEED_URL% -Verbosity detailed -NonInteractive
