
variables:
  version: "2018.7.13.6291"

stages:
  - debug
  - release

debug:
  stage: debug
  only:
  - debug
  script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
  - dotnet build "Bhbk.Lib.Core.sln" --configuration Release
  - dotnet test "Bhbk.Lib.Helpers.Tests\Bhbk.Lib.Helpers.Tests.csproj" --configuration Release
  - dotnet test "Bhbk.Lib.Waf.Tests\Bhbk.Lib.Waf.Tests.csproj" --configuration Release

release:
  stage: release
  only:
  - dummy
  script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
  - dotnet build --verbosity quiet "Bhbk.Lib.Core.sln" --configuration Release
  - dotnet pack "Bhbk.Lib.Helpers\Bhbk.Lib.Helpers.csproj" -p:PackageVersion=$version --output ".." --configuration Release -p:TargetFrameworks=netstandard2.0
  - dotnet pack "Bhbk.Lib.Waf\Bhbk.Lib.Waf.csproj" -p:PackageVersion=$version --output ".." --configuration Release -p:TargetFrameworks=netstandard2.0
  - dotnet nuget push *.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
