
before_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"

stages:
    - build
    - test
    - deploy

build:
  stage: build
  only:
    - dummy
  script:
    - cd Arch(.NetFramework)
    - dotnet restore Bhbk.Lib.sln --no-cache --verbosity quiet
    - nuget restore Bhbk.Lib.DataAccess.EF\Bhbk.Lib.DataAccess.EF.csproj -SolutionDirectory . -NoCache -Verbosity quiet
    - dotnet build Bhbk.Lib.sln --configuration Release --verbosity quiet /p:platform=x64
    - cd ..\Arch(.NetStandard)
    - dotnet restore Bhbk.Lib.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Lib.sln --configuration Release --verbosity quiet /p:platform=x64

test:
  stage: test
  only:
    - dummy
  script:
    - cd Arch(.NetFramework)
    - dotnet restore Bhbk.Lib.sln --no-cache --verbosity quiet
    - nuget restore Bhbk.Lib.DataAccess.EF\Bhbk.Lib.DataAccess.EF.csproj -SolutionDirectory . -NoCache -Verbosity quiet
    - nuget restore Bhbk.Lib.DataAccess.EF.Tests\Bhbk.Lib.DataAccess.EF.Tests.csproj -SolutionDirectory . -NoCache -Verbosity quiet
    - dotnet build Bhbk.Lib.sln --configuration Release --verbosity quiet /p:platform=x64
    - dotnet test Bhbk.Lib.DataAccess.EF.Tests\Bhbk.Lib.DataAccess.EF.Tests.csproj --configuration Release /p:platform=x64
    - cd ..\Arch(.NetStandard)
    - dotnet restore Bhbk.Lib.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Lib.sln --configuration Release --verbosity quiet /p:platform=x64
    - dotnet test Bhbk.Lib.DataAccess.EFCore.Tests\Bhbk.Lib.DataAccess.EFCore.Tests.csproj --configuration Release /p:platform=x64 /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.Lib.DataState.Tests\Bhbk.Lib.DataState.Tests.csproj --configuration Release /p:platform=x64 /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.Lib.QueryExpression.Tests\Bhbk.Lib.DataState.Tests.csproj --configuration Release /p:platform=x64 /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.Lib.Waf.Tests\Bhbk.Lib.Waf.Tests.csproj --configuration Release /p:platform=x64 /p:CollectCoverage=true /p:CoverletOutput=bin\Release\

deploy:
  stage: deploy
  only:
    - dummy
  script:
    - set VERSION=2020.03.04.2045
    - cd Arch(.NetFramework)
    - dotnet restore Bhbk.Lib.sln --no-cache --verbosity quiet
    - nuget restore Bhbk.Lib.DataAccess.EF\Bhbk.Lib.DataAccess.EF.csproj -SolutionDirectory . -NoCache -Verbosity quiet
    - nuget restore Bhbk.Lib.DataAccess.EF.Tests\Bhbk.Lib.DataAccess.EF.Tests.csproj -SolutionDirectory . -NoCache -Verbosity quiet
    - dotnet build Bhbk.Lib.sln --configuration Release --verbosity quiet /p:platform=x64
    - nuget pack Bhbk.Lib.DataAccess.EF\Bhbk.Lib.DataAccess.EF.csproj -Version %VERSION% -OutputDirectory . -Properties Configuration=Release -Properties Platform=x64
    - cd ..\Arch(.NetStandard)
    - dotnet restore Bhbk.Lib.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Lib.sln --configuration Release --verbosity quiet /p:platform=x64
    - dotnet pack Bhbk.Lib.CommandLine\Bhbk.Lib.CommandLine.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - dotnet pack Bhbk.Lib.Common\Bhbk.Lib.Common.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - dotnet pack Bhbk.Lib.Cryptography\Bhbk.Lib.Cryptography.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - dotnet pack Bhbk.Lib.DataAccess.EFCore\Bhbk.Lib.DataAccess.EFCore.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - dotnet pack Bhbk.Lib.DataState\Bhbk.Lib.DataState.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - dotnet pack Bhbk.Lib.Hosting\Bhbk.Lib.Hosting.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - dotnet pack Bhbk.Lib.QueryExpression\Bhbk.Lib.QueryExpression.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - dotnet pack Bhbk.Lib.Waf\Bhbk.Lib.Waf.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - cd ..
    - dotnet nuget push Arch(.NetFramework)\*.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
    - dotnet nuget push Arch(.NetStandard)\*.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
    - set VERSION=
